project_id = "spring-nest"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/**", "http://localhost:3000/**"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
